config/routes.rb
Rails.application.routes.draw do
  get '/users/auth/:service/callback' => 'user_services#create'
  devise_for :users

  get '/users/auth/:service/callback' => 'user_services#create'
  # resources :user_services, :only => [:create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :tags
    end
  end

  resources :tags do
  end

  get 'gems' => 'projects#gems', as: :gems
  get 'apps' => 'projects#apps', as: :apps
  get '/new' => 'projects#new', as: :new_project
  resources :projects, path: '/' do
    get '/*full_name/edit' => 'projects#edit', on: :collection, as: :edit
    get '/*full_name' => 'projects#show', on: :collection, as: :show
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include ActiveModel::Validations

  has_many :stats, class_name: 'Stats'
  has_many :project_tags
  has_many :tags, through: :project_tags
  belongs_to :user

  paginates_per 20

  # default_scope { select('*, hottness(projects.*) AS hottness') }
  scope :hot,    -> { order(hottness: :desc) }
  scope :top,    -> { order points: :desc }
  scope :recent, -> { order created_at: :desc }
  scope :gems,   -> { where is_gem: true }
  scope :apps,   -> { where is_app: true }

  validates_format_of :full_name, with: /.+\/.+/
  validates :full_name, presence: true, uniqueness: true, github_repo: true
  validates :rubygem_name, presence: true, rubygem_gem: true, if: :is_gem

  validates_with ProjectTypeValidator, attributes: [:is_gem, :is_app]

  def calculate_points
    stargazers_count + \
    forks_count + \
    subscribers_count
  end

  def calculate_hottness
    period_stats = stats.where('created_at > ?', DateTime.now - 2.days)

    first_sum  = period_stats.first.stargazers_count
    first_sum += period_stats.first.subscribers_count
    first_sum += period_stats.first.forks_count

    last_sum   = period_stats.last.stargazers_count
    last_sum  += period_stats.last.subscribers_count
    last_sum  += period_stats.last.forks_count

    delta = last_sum - first_sum
    update_attribute(:hottness, delta)
  end

  def fetch_data
    fetch_github_data
    fetch_rubygem_data
    touch_points
    calculate_hottness
  end

  def touch_points
    update_attribute(:points, calculate_points)
  end

  def save_project_stats(opts = {})
    stats_for_today = stats.today

    # If there are any stats saved for today,
    # do not create a new ones, just udate the existing ones.
    if stats_for_today.any?
      stats_for_today.last.update_attributes(opts)
    else
      stats.create(opts)
    end
  end

  def type
    type = nil
    type = :gem if is_gem
    type = :app if is_app
    type
  end

  def points_this_month
    s = stats.this_month
    s.last.points - s.first.points
  end

  def downloads
    stats.last.rubygem_downloads_count
  end

  def percentage_gain_this_month
    gains = {}
    %w(
      stargazers_count rubygem_downloads_count subscribers_count
      forks_count
    ).each do |key|
      gains[key.to_sym] = stats.percentage_gain_this_month(key.to_sym)
    end

    gains
  end

  def gem_downloads
    stats.last.try(:rubygem_downloads_count) || 0
  end

  private

  def fetch_github_data
    Github::ProjectRepoService.new(self).sync
  end

  def fetch_rubygem_data
    return false unless rubygem_name.present?

    Rubygems::ProjectGemService.new(self).sync
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all.page(params[:page])
    @projects_count = Project.count(:id)
    apply_scope_filters
  end

  # GET /gems
  def gems
    @projects = Project.gems.page(params[:page])
    @projects_count = Project.gems.count(:id)
    apply_scope_filters
  end

  # GET /projects
  def apps
    @projects = Project.apps.page(params[:page])
    @projects_count = Project.apps.count(:id)
    apply_scope_filters
  end

  # GET /projects/1
  def show
    @project = @project.decorate
  end

  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params).decorate
    @project.user = current_user

    if @project.save
      @project.fetch_data
      redirect_to @project.path, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  # def update
  #   respond_to do |format|
  #     if @project.update(project_params)
  #       format.html { redirect_to @project, notice: 'Project was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @project }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @project.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find_by(full_name: params[:full_name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:full_name, :is_gem, :is_app, :rubygem_name, :tag_ids => [])
    end

    def apply_scope_filters
      @projects = case params[:scope]
        when 'top'    then @projects.top
        when 'recent' then @projects.recent
        else @projects.hot
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
= form_for @project do |f|
  .row ng-controller="ProjectFormCtrl"
    .col-xs-8.col-xs-offset-2

      / Pass @project params to angular controller
      div ng-init="project.isGem=#{@project.is_gem}"
      div ng-init="project.isApp=#{@project.is_app}"
      div ng-init="setTags([#{@project.tag_ids.join(',')}])"

      - if @project.errors.any?
        .alert.alert-danger
          h4 There are some errors in the form:
          ul
            - @project.errors.full_messages.each do |message|
              li = message

        hr

      .form-group
        = f.label :full_name, 'GitHub path:'
        = f.text_field :full_name, class: 'form-control input-lg text-center', placeholder: 'owner/repo'
        hr

      .form-group
        .row
          .col-xs-6.text-center
            label Is that a gem?
            br
            .checkbox.btn.btn-default: label
              = f.check_box :is_gem, ng_model: 'project.isGem'
              | Yes

          .col-xs-6.text-center
            label Is that an app?
            br
            .checkbox.btn.btn-default: label
              = f.check_box :is_app
              | Yes

      .form-group ng-show="project.isGem"
        hr
        = f.label :rubygem_name, 'Rubygem name:'
        = f.text_field :rubygem_name, class: 'form-control input-lg text-center'
        p.help-block.text-center How is that gem called on <a href="http://rubygems.org">rubygems.org</a>?

      .form-group
        hr

        label Project tags:
        ui-select multiple="" ng-model="item.tags" theme="select2"
          ui-select-match placeholder="Select tags"
            | {{ $item.name }}

          ui-select-choices repeat="tag in tags | filter: {name: $select.search}"
            strong
              | {{ tag.name }}
              br
            small.text-muted
              | {{ tag.description }}

        input.hidden type="text" name="project[tag_ids][]" ng-repeat="tag in item.tags" ng-model="tag.id"

      hr

      .text-center
        input.btn.btn-default type="submit" value="Save project"

app/views/projects/apps.html.slim
- content_for :sidebar_left do
  = render_cell :scope_sidebar, :show, root_path: apps_path

.page-heading.text-center
  h1.page-title Applications
  p.lead.text-muted There are #{@projects_count} apps on rubbby
  hr

- @projects.each do |project|
  = render_cell :project, :list_show, project: project

= paginate @projects

app/views/projects/edit.html.slim
.text-center
  h2.page-title Editing project
  p.lead.text-muted Provide basic project info to add it to rubbby:

hr

== render 'form'

app/views/projects/gems.html.slim
- content_for :sidebar_left do
  = render_cell :scope_sidebar, :show, root_path: gems_path

.page-heading.text-center
  h1.page-title Gems
  p.lead.text-muted There are #{@projects_count} gems on rubbby
  hr

- @projects.each do |project|
  = render_cell :project, :list_show, project: project

= paginate @projects

app/views/projects/index.html.slim
- content_for :sidebar_left do
  = render_cell :scope_sidebar, :show, root_path: projects_path

- @projects.each do |project|
  = render_cell :project, :list_show, project: project

= paginate @projects

app/views/projects/new.html.slim
.text-center
  h2.page-title New project
  p.lead.text-muted Provide basic project info to add it to rubbby:

hr

== render 'form'

app/views/projects/newx.html.slim
h2.page-title New project
p.lead.text-muted Are you sure you wan't to add it?

.panel.panel-default
  .panel-body
    .media
      .pull-left
        = image_tag 'gh_logo.png', size: '60', class: 'img-rounded'

      .media-body
        h3.media-heading
          a href=@gh_repo.html_url
            = @gh_repo.full_name

        p.no-margin
          = @gh_repo.description
          - if @gh_repo.homepage.present?
            == " - #{link_to @gh_repo.homepage, @gh_repo.homepage}"

= form_for @project, url: '/' do |f|
  = f.hidden_field :full_name

  .text-center
    ul.list-inline
      li: button.btn.btn-success type="submit" Sure i do!
      li: a.btn.btn-default href=new_project_path Naah

app/views/projects/show.html.slim
div ng-controller="ProjectShowCtrl"
  .page-heading.text-center
    h1.page-title = @project.name
    p.lead.text-muted = @project.description

    ul.list-inline
      - @project.tags.decorate.each do |tag|
        li= link_to tag.path, class: 'label label-tag' do
          span
            = tag
            span.badge 12

  hr

  h4.page-title-section This month
  ul.list-unstyled.stats
    li.stats-element
      .media
        .pull-left.stats-chart
          .stats-chart-number.text-success +8%
          nvd3 options="chartOpts" data="[{y: 8, color: 'green'}, {y: 92, color: '#eee'}]"
        .media-body
          h3.stats-number.text-success 18
          .stats-label Commits
          .stats-total-count 387 total

    li.stats-element
      .media
        .pull-left.stats-chart
          .stats-chart-number.text-success = @project.percentage_gain(:points)
          nvd3 options="chartOpts" data="[{y: 48, color: 'green'}, {y: 52, color: '#eee'}]"
        .media-body
          h3.stats-number.text-success = @project.points_this_month
          .stats-label Points
          .stats-total-count #{@project.mini_points} total

    li.stats-element
      .media
        .pull-left.stats-chart
          .stats-chart-number.text-danger = @project.percentage_gain(:rubygem_downloads_count)
          nvd3 options="chartOpts" data="[{y: 20, color: '#eee'}, {y: 80, color: '#c54b4b'}]"
        .media-body
          h3.stats-number.text-danger 12k
          .stats-label Downloads
          .stats-total-count #{@project.mini_downloads} total

  hr

  - 3.times do
    .media
      a.pull-left
        = image_tag 'https://avatars0.githubusercontent.com/u/581569?v=2&s=35', class: 'img-circle'
      .media-body
        strong Mike Bajur
        p.text-muted 28 days ago

    p Jeans are so personal and each pair, each style can be treated very differently. It really depends on how you want your jeans to look.
    p If you like to keep that deep blue color; don't wash them. If you buy an expensive/rare pair of selvedge or hand-dyed indigo jeans I also recommend that you never wash them. You can instead leave them in the freezer to break down odor and bacteria. If you are looking to get rid of general dirt buildup that happens over time you can "home dry-clean" them in your drier (inside out). I recommend that every 2 months. You can also gently soak them in a bathtub in cold water for an hour; this will lift a lot of dirt out of the jeans without losing significant color. I recommend this once a year or every other year. This also has the added benefit of tightening the denim weave. They jeans will feel tighter and stretched ereas like the knees etc will be less noticeable.
    p If you like your jeans to be really worn in and faded and get that soft, comfortable feel, then go ahead and wash them after wearing them a couple of times. If you use cold water the fading will happen more slowly.
    hr

  .form-group
    textarea.form-control placeholder="Write your comment to #{@project.name} here..."




- content_for :sidebar_left do
  / ul.list-unstyled.text-right.project-stats
  /   li.stats-element class=@project.hottness_score_class
  /     h3.stats-number
  /       i.glyphicon.glyphicon-fire>
  /       = @project.hottness
  /     .stats-label Hottness
  /   li.with-separator
  /     h3.stats-number = @project.mini_points
  /     .stats-label Points
  /   li
  /     h3.stats-number= @project.mini_time_ago(:github_pushed_at)
  /     .stats-label Recent push
  /   li
  /     h3.stats-number 12
  /     .stats-label Releases

  /   li.active
  /     h3.stats-number 12
  /     .stats-label Comments

- content_for :sidebar_right do

  ul.list-unstyled.nav-general
    li.active: a Overall
    li: a GitHub
    li: a Rubygems
    li: a Discussions